### ISSUE TITLE
Unified file encoding to UTF-8

### ISSUE THREAD

**Issue by grapherd** [LITEOS/LiteOS_Kernel#10]
Hi all, 

The source file in api_example are now using GBK encoding.

Maybe we should convert this to UTF-8 first,
thanks.

**Comment by grapherd** [comment]
I'm wrong, it seem just only `los_api_list.c` have this problem.

**Comment by zhoubo85** [comment]
we will convert it, maybe a few days later

**Comment by zhoubo85** [comment]
This problem is fixed.
