### ISSUE TITLE
有没有移植STM32L152低功耗MCU的范例？

### ISSUE THREAD

**Issue by jiekechoo** [LITEOS/LiteOS_Kernel#115]
如题，现在希望社区给与帮助。谢谢

**Comment by lichao93** [comment]
新建内核工程可参考：https://github.com/LITEOS/LiteOS_Kernel/blob/master/doc/LiteOS_Migration_Guide_Keil.md，驱动移植过程可参考stm32f103，注意下载对应的pack包进行安装，并下载相应的BSP包进行驱动适配，区别不大。

**Comment by jiekechoo** [comment]
@lichao93 STM32F103和L152虽然都是M3系列，但是，F103用库函数，L152用的HAL库，完全两样的。

**Comment by lichao93** [comment]
我所说的是过程一样，L152用的HAL库那就用HAL库来适配驱动，目前已支持的ST系列芯片其实都是适配的BSP包中的HAL代码，适配时有具体的问题可以在github或者论坛上提出来！

**Comment by jiekechoo** [comment]
自己移植成功了
