### ISSUE TITLE
How to build LiteOS by GCC toolchain

### ISSUE THREAD

**Issue by lulouie** [LITEOS/LiteOS_Kernel#14]
Are there anyway to build LiteOS by GCC toolchain, it seem we can now only build from IAR embedded workbench and Keil.

Both of the IDE can't use it on Linux.

Thanks.

**Comment by Supowang** [comment]
LiteOS can build by GCC toolschain. But from now on ,we run LiteOS on ARM Cortex M use iar or Keil  as example.I am sorry for this，Please wait a GCC version，We will provide soon.

**Comment by BaikalHu** [comment]
close it.

**Comment by BaikalHu** [comment]
Closed #14 via b29d4036
