### ISSUE TITLE
interrupt management should do more

### ISSUE THREAD

**Issue by ffun** [LITEOS/LiteOS_Kernel#19]
example code in Guide book "中断机制，编程实例"
```cpp
#include "los_hwi.h"
#include "los_typedef.h"
#define HWI_NUM_INT50 50
void uart_irqhandle(int irq,void *dev)
{
    printf("\n int the func uart_irqhandle \n");
}
void hwi_test()
{
    int a = 1;
    UINTPTR uvIntSave;
    uvIntSave = LOS_IntLock();
    LOS_HwiCreate(HWI_NUM_INT50, 0,0,uart_irqhandle,NULL);//创建中断
    hal_interrupt_unmask(HWI_NUM_INT50);
    LOS_IntRestore(uvIntSave);
    hal_interrupt_mask(HWI_NUM_INT50);
}
```
- 示例有问题  
问题1：把找不到的`hal_interrupt_mask`注释掉。实测：
问题2：直接这么写的话，当触发串口中断，会`一直`printf内容出来。需要在printf前清中断标志位。
- 如果需要手动清中断，则与手册的中断管理内容不符合  
在 "中断机制，概述"中，“Huawei LiteOS的中断机制支持中断共享，Huawei LiteOS的中断机制支持中断底半部，底半部基于workqueue”  
workqueue即任务队列，中断后是直接遍历queue处理，没必要每个queue都去手动清标志位吧。这方面是否可以做的更完善？

**Comment by zhoubo85** [comment]
恩，中断的示例说明已经更新到相关文档中了，可以到doc目录下的文档中阅读，或者直接查看los_api_interrupt.c中的代码
