### ISSUE TITLE
api接口手册

### ISSUE THREAD

**Issue by Wxinfeng** [LITEOS/LiteOS_Kernel#20]
能否提供一下API接口手册，不是开发指南，这样用起来毕竟省事

**Comment by zhoubo85** [comment]
doc目录下HuaweiLiteOSKernelDevGuide就是关于api的相关手册

**Comment by zhoubo85** [comment]
doc目录下HuaweiLiteOSKernelDevGuide就是关于api的相关手册

**Comment by Wxinfeng** [comment]
看到了   但是那个开发指南感觉太简略。不过还能凑合看
麻烦你解决一下我刚刚提的问题
因为我完全按照官方的例程用的，出来的结果却不一样
