### ISSUE TITLE
los_api_task这个例程编译后跑的结果跟开发指南的不一样

### ISSUE THREAD

**Issue by Wxinfeng** [LITEOS/LiteOS_Kernel#21]
调试时程序死在oshwidefaulthandler这个函数的while(1)
烧写完后串口打印的是这些
LOS_TaskLock() Success!

Example_TaskHi create Success!

Example_TaskLo create Success!

Enter TaskHi Handler.

Enter TaskLTaskHi LOS_TaskDelay Done.

 Handler.

复位后就收到是
LOS_TaskLock() Success!

Example_TaskHi create Success!

Example_TaskLo create Success!

**Comment by zhoubo85** [comment]
从现象上看的话，LiteOS没有正常跑起来。你是否加入了其他的代码到LiteOS工程中？

**Comment by Wxinfeng** [comment]
现在已经跑起来了，但是中断的那个demo依然没有跑起来。
卡死在上面的那个地方。我就加入了一个串口初始化的部分，方便打印的东西可以通过串口查看。其余的都没动。

**Comment by Wxinfeng** [comment]
其余的几个example都能正常打印，唯独los_api_interrupt.c无法打印串口信息

**Comment by Wxinfeng** [comment]
我好想找到毛病了，我在f103上面跑的。应该是这个地方的问题，我重新写一下这块试试

**Comment by Wxinfeng** [comment]
解决了，重新写了一个正常了
谢谢啦

**Comment by zhoubo85** [comment]
恩，目前开放的代码只做了stm32f429和f411的验证，后续会有其他开发板的支持。
