### ISSUE TITLE
BugReport：undefined interface in los_queue.h, LOS_QueueReadCopy and LOS_QueueWriteCopy

### ISSUE THREAD

**Issue by buruifeng** [LITEOS/LiteOS_Kernel#22]
In the Huawei LiteOS 2017 Hackthon, Beijing Station, one of the programmers found there were two interfaces declared in header files los_queue.h, but "undefined error" was reported during the linking process.

After a debugging, I found there's no definition, which need to be fixed.

**Comment by zhoubo85** [comment]
we will delete it later
