### ISSUE TITLE
Need to be optimized: delay_ms() or delay_us() of the 3rd party drivers will trigger interruption during the hardware initialization.

### ISSUE THREAD

**Issue by buruifeng** [LITEOS/LiteOS_Kernel#23]
Need to be optimized: 
delay_ms() or delay_us() of the 3rd party drivers will trigger interruption during the hardware initialization.

A common way of using Huawei LiteOS would be run through the original demo code without operating system, and then integrate it with LiteOS. 
Since Huawei LiteOS has already take over the system tick interruption, so the delay_ms() interface of 3rd party drivers will trigger exception and the whole initialization will fail. I think there should be a way to allow the programmers to use delay method during the initialization.

**Comment by liuxuming** [comment]
should implement this function with hardware timer, and...don't use systick timer that already used by Kernel.
