### ISSUE TITLE
how about LiteOS_Migration_Guide_keil.md

### ISSUE THREAD

**Issue by xiaoyusu** [LITEOS/LiteOS_Kernel#29]
two docs based on DISCO-STM32F429 with keil
one is the LiteOS_Migration_Guide_keil.md, the other one is LiteOS_Migration_Guide_stm32f429_Keil.md

which is standard?

**Comment by lichao93** [comment]
《LiteOS_Migration_Guide_keil.md》for common migration guide,《LiteOS_Migration_Guide_stm32f429_Keil.md》for device driver。
