### ISSUE TITLE
和μCOS有什么区别？

### ISSUE THREAD

**Issue by ascend-hgx** [LITEOS/LiteOS_Kernel#34]

**Comment by liuxuming** [comment]
Huawei LiteOS在内核技术上跟各种通用RTOS是差不多的，在实现上各有各的方式。不过Huawei LiteOS在物联网方案上明显更有优势。

**Comment by qingsongcw** [comment]
Hi, Can you explain it to me which point demonstrates that liteos advances other os?

**Comment by one-next** [comment]
Because it made in china. HA,HA!!! @qingsongcw

**Comment by liuxuming** [comment]
LiteOS本身具备对接云平台的中间件,是轻量级的开源物联网操作系统. 请参考相关官方发布的信息.
