### ISSUE TITLE
Porting Huawei LiteOS to NXP platform

### ISSUE THREAD

**Issue by liuxuming** [LITEOS/LiteOS_Kernel#35]
NXP is an important IC/Sensor manufacturer , We should support the LPC series mcu.

**Comment by qingsongcw** [comment]
Hi,this is the first time to study liteos. i find this os bases on some specific mcus, although some mcus' core are same. at this time, the difference between mcus basing on the same core often happens on the mcu's peripherals ,such as UART,SPI,and so on. if adding HAL layer managing such peripherals, liteos maybe more easier for immigrating. i think it will be independent with specific mcu, only depending on the mcu's core.

**Comment by liuxuming** [comment]
good idea, the HAL(or driver model) is being developed,
