### ISSUE TITLE
Code Style is not so good.

### ISSUE THREAD

**Issue by larzhang2** [LITEOS/LiteOS_Kernel#46]
I have just reviewed usr/main.c and found that there were a few meaningless blank space in the end of line and tab space in the beginning of line. I suggest you guys could use vim plug-in unit for detecting this code style issue. 

As Huawei is an influent IT company, I think it's better to make the source codes to look beautiful.

![screen shot 2017-04-01 at 2 50 43 pm](https://cloud.githubusercontent.com/assets/19813155/24576234/a5ed3e94-16ea-11e7-8a84-67cc56fb7bc8.png)

**Comment by liuxuming** [comment]
thanks, we'll improve immediately.

**Comment by larzhang2** [comment]
https://github.com/google/styleguide/tree/gh-pages/cpplint
Maybe this tool is helpful for you guys.
