### ISSUE TITLE
您好，關於STM32Cube

### ISSUE THREAD

**Issue by RozenAstrayChen** [LITEOS/LiteOS_Kernel#75]
您好，我看您[stm32f411re文檔](https://github.com/LITEOS/LiteOS_Kernel/blob/master/doc/LiteOS_Migration_Guide_stm32f411_Keil.md)，下載STM32CubeF4這邊寫成STM32CubeL4了。
[STM32CubeF4 1.16連結](http://www.st.com/content/st_com/en/products/embedded-software/mcus-embedded-software/stm32-embedded-software/stm32cube-embedded-software/stm32cubef4.html)
![Uploading 螢幕快照 2017-05-19 上午12.56.23.png…]()

**Comment by lichao93** [comment]
谢谢您发现的问题，马上修改！
