### ISSUE TITLE
interrupt create failed

### ISSUE THREAD

**Issue by RozenAstrayChen** [LITEOS/LiteOS_Kernel#77]
hi i use **los_api_interrupt.c** but,I got failed in 
`		uwRet=LOS_HwiCreate(6,0,0,EXTI0_IRQHandler,NULL);` 
i dont know why?
My EVB use STM32F407
[code](https://github.com/RozenAstrayChen/LiteOS_stm32f407/tree/master/09-LiteOS_F407)

**Comment by RozenAstrayChen** [comment]
i got error value is `OS_ERRNO_HWI_ALREADY_CREATED`
and it say ** * Solution: Check whether the interrupt specified by the passed-in interrupt number has already been created.
**

**Comment by zhoubo85** [comment]
in los_bsp_adapter.c  there is const 
const unsigned char g_use_ram_vect = 0;, 
you should make it to 1, then you can use LOS_HwiCreate

**Comment by lichao93** [comment]
IRQ number should add 16 ，if you IRQ number is 6，fill 22 int it。

**Comment by 18959697616** [comment]
Excuse me，求STMF746ZG 开发板与pc连接的驱动程序

**Comment by zhoubo85** [comment]
http://www.st.com/content/st_com/en/products/embedded-software/development-tool-software/stsw-link009.html

**Comment by RozenAstrayChen** [comment]
OK i got it!
