### ISSUE TITLE
Dependency of los_bsp_flash.c?

### ISSUE THREAD

**Issue by stanely** [LITEOS/LiteOS_Kernel#79]
From the source code of `los_bsp_flash.c,` it seems to me it offers the wrapper layer of fatfs, not flash itself.
I am wondering to have the way to access the raw flash data via any pre-defined interface just like `los_bsp_{module_name}`.

Please advise it, thanks.

**Comment by lichao93** [comment]
you can refer to 《LiteOS_Migration_Guide_FatFs_Keil.md》：https://github.com/LITEOS/LiteOS_Kernel/blob/master/doc/LiteOS_Migration_Guide_FatFs_Keil.md
